# Generated by Django 6.0.2 on 2026-02-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="doctors",
            field=models.ManyToManyField(to="main.doctor"),
        ),
    ]
