# Generated by Django 6.0.2 on 2026-02-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_clinic_doctors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="gender",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="gender",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.BooleanField(default=False),
        ),
    ]
