# Generated by Django 6.0.2 on 2026-02-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_admin_gender_alter_doctor_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="date_end_work",
            field=models.DateField(blank=True, null=True),
        ),
    ]
