# Generated by Django 6.0.2 on 2026-02-10 19:37

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_doctor_date_end_work"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="history_education",
            field=models.JSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
    ]
