# Generated by Django 6.0.2 on 2026-02-15 21:15

import django.core.serializers.json
import django.db.models.deletion
import main.validation_model
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_education_history_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clinic', verbose_name='ForeignKey на клинику'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.EmailField(max_length=200, unique=True, verbose_name='Почта пользователя'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='family',
            field=models.CharField(max_length=100, verbose_name='Фамилия пользователя'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='gender',
            field=models.BooleanField(default=False, verbose_name='Пол пользователя'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Флаг удаленности аккаунта пользователя'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=100, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона пользователя'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='second_name',
            field=models.CharField(max_length=100, verbose_name='Отчество пользователя'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='doctors',
            field=models.ManyToManyField(to='main.doctor', verbose_name='m2m связь с таблицей врачей'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Флаг удаленности клиники'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='juridical_address',
            field=models.CharField(max_length=1000, verbose_name='Юридический адрес клиники'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название клиники'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='physical_address',
            field=models.CharField(max_length=1000, verbose_name='Физический адрес клиники'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clinic', verbose_name='ForeignKey на клинику'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания консультации'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doctor', verbose_name='ForeignKey на врача'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата конца консультации'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='флаг удалённости консультации'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient', verbose_name='ForeignKey на пациента'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата начала консультации'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления консультации'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='date_birth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='date_end_work',
            field=models.DateField(blank=True, null=True, verbose_name='Дата конца работы'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='date_start_work',
            field=models.DateField(verbose_name='Дата начала работы'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=200, unique=True, verbose_name='Почта пользователя'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.IntegerField(verbose_name='Опыт врача'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='family',
            field=models.CharField(max_length=100, verbose_name='Фамилия пользователя'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.BooleanField(default=False, verbose_name='Пол пользователя'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Флаг удаленности аккаунта пользователя'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='password',
            field=models.CharField(max_length=100, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона пользователя'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='salary',
            field=models.IntegerField(verbose_name='Зарплата врача'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='second_name',
            field=models.CharField(max_length=100, verbose_name='Отчество пользователя'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(max_length=200, verbose_name='Специализация врача'),
        ),
        migrations.AlterField(
            model_name='education',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doctor', verbose_name='ForeignKey на врача'),
        ),
        migrations.AlterField(
            model_name='education',
            name='history_education',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='История обучения врача'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=200, unique=True, verbose_name='Почта пользователя'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='family',
            field=models.CharField(max_length=100, verbose_name='Фамилия пользователя'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.BooleanField(default=False, verbose_name='Пол пользователя'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Флаг удаленности аккаунта пользователя'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='password',
            field=models.CharField(max_length=100, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона пользователя'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='second_name',
            field=models.CharField(max_length=100, verbose_name='Отчество пользователя'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tag_social',
            field=models.CharField(max_length=100, validators=[main.validation_model.validate_social_tag], verbose_name='Имя аккаунта в социальных сетях'),
        ),
    ]
