# Generated by Django 6.0.2 on 2026-02-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_admin_clinic_alter_admin_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="salary",
            field=models.IntegerField(null=True, verbose_name="Зарплата врача"),
        ),
    ]
