# Generated by Django 6.0.2 on 2026-02-19 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_doctor_salary"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvTraining",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=400)),
                ("specialty", models.CharField(max_length=100)),
                ("start_date", models.DateField(verbose_name="Дата начала обучения")),
                ("end_date", models.DateField(verbose_name="Дата конца обучения")),
                (
                    "education",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.education",
                        verbose_name="ForeignKey на образование",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Ordination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=400)),
                ("specialty", models.CharField(max_length=100)),
                ("start_date", models.DateField(verbose_name="Дата начала обучения")),
                ("end_date", models.DateField(verbose_name="Дата конца обучения")),
                (
                    "education",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.education",
                        verbose_name="ForeignKey на образование",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=400)),
                ("specialty", models.CharField(max_length=100)),
                ("start_date", models.DateField(verbose_name="Дата начала обучения")),
                ("end_date", models.DateField(verbose_name="Дата конца обучения")),
                (
                    "education",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.education",
                        verbose_name="ForeignKey на образование",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
